# Generated by Django 2.0.8 on 2019-08-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_description', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='gallery/image/')),
            ],
        ),
    ]
