# Generated by Django 2.0.8 on 2019-08-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
