# Generated by Django 2.0.8 on 2019-09-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20190826_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_heading', models.CharField(max_length=100)),
                ('image_description', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
